version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Only allow updates to the dependency graph and security updates
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    # Add a message to allow Dependabot to auto-merge minor and patch updates
    commit-message:
      prefix: "chore(deps): "
      include: "scope"
    # Group updates by dependency type
    groups:
      production-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "github-actions"
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(actions): "
      include: "scope"
