name: Deploy to Hugging Face

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Hugging Face
        run: |
          echo ${{ secrets.HF_TOKEN }} | docker login -u ${{ secrets.HF_USERNAME }} --password-stdin
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.HF_USERNAME }}/agent4-implementation:latest
          build-args: |
            NODE_ENV=production
      
      - name: Update Space
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"repository":"${{ github.repository }}", "revision":"${{ github.sha }}"}' \
            https://huggingface.co/api/spaces/${{ secrets.HF_USERNAME }}/agent4-implementation/redeploy
