name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        build-args: |
          NODE_ENV=production
    
    - name: Deploy to Hugging Face Spaces
      uses: hf-actions/deploy-to-space@v1
      with:
        space: ${{ github.repository }}
        docker_username: ${{ github.actor }}
        docker_password: ${{ secrets.GITHUB_TOKEN }}
        docker_image: ghcr.io/${{ github.repository }}:latest
        space_sdk: docker
        env_vars: |
          HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}
          ALIBABA_QWEN_API_KEY=${{ secrets.ALIBABA_QWEN_API_KEY }}
          KIMI_API_KEY=${{ secrets.KIMI_API_KEY }}
          MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}
          DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}
          OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
          CODESTRAL_API_KEY=${{ secrets.CODESTRAL_API_KEY }}
          NODE_ENV=production
          PORT=3000
